//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132204.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVu()
        {
            this.HoaDonDichVus = new HashSet<HoaDonDichVu>();
        }

        [DisplayName("Mã DV")]
        [Required(ErrorMessage = "Chưa nhập mã DV")]
        public int MaDV { get; set; }
        [DisplayName("Tên DV")]
        [Required(ErrorMessage = "Chưa nhập tên DV")]
        public string TenDV { get; set; }
        [DisplayName("Mã LDV")]
        [Required(ErrorMessage = "Chưa nhập mã loại dịch vụ")]
        public Nullable<int> MaLDV { get; set; }
        [DisplayName("Giá")]
        [Required(ErrorMessage = "Chưa nhập Giá")]
        public int Gia { get; set; }
        [DisplayName("Số lượng tồn kho")]
        [Required(ErrorMessage = "Chưa nhập số lượng")]
        public int TonKho { get; set; }
        [DisplayName("Đơn vị tính")]
        [Required(ErrorMessage = "Chưa nhập đơn vị tính")]
        public string DonVi { get; set; }
        [DisplayName("Ảnh")]
        [Required(ErrorMessage = "Chưa nhập ảnh")]
        public string Anh { get; set; }
    
        public virtual LoaiDichVu LoaiDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDichVu> HoaDonDichVus { get; set; }
    }
}
