//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132204.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HoaDonDatPhong
    {
        [DisplayName("Mã đặt phòng")]
        [Required(ErrorMessage = "Chưa nhập mã đặt phòng")]
        [StringLength(10)]
        public string MaDatPhong { get; set; }

        [DisplayName("Mã Nhân viên")]
        [Required(ErrorMessage = "Chưa nhập mã nhân viên")]
        [StringLength(10)]
        public string MaNV { get; set; }

        [DisplayName("Mã khách hàng")]
        [Required(ErrorMessage = "Chưa nhập mã khách hàng")]
        [StringLength(10)]
        public string MaKH { get; set; }

        [DisplayName("Mã phòng")]
        [Required(ErrorMessage = "Chưa nhập mã phòng")]
        [StringLength(10)]
        public string MaPhong { get; set; }

        [DisplayName("Ngày đặt")]
        [Required(ErrorMessage = "Chưa nhập ngày đặt")]
        [DisplayFormat(DataFormatString = "{0,dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayDat { get; set; }
        [DisplayName("Ngày vào")]
        [Required(ErrorMessage = "Chưa nhập ngày vào")]
        [DisplayFormat(DataFormatString = "{0,dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayVao { get; set; }
        [DisplayName("Ngày trả")]
        [Required(ErrorMessage = "Chưa nhập ngày trả phòng ")]
        [DisplayFormat(DataFormatString = "{0,dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayRa { get; set; }
        [DisplayName("Tình  Trạng")]
        [Required(ErrorMessage = "Chưa nhập ngày tình trạng ")]
        public bool ThanhToan { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
