//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132204.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDonDatPhongs = new HashSet<HoaDonDatPhong>();
            this.HoaDonDichVus = new HashSet<HoaDonDichVu>();
        }

        [DisplayName("Mã số KH")]
        [Required(ErrorMessage = "Chưa nhập mã KH")]
        [StringLength(10)]
        public string MaKH { get; set; }

        [DisplayName("Họ KH")]
        [Required(ErrorMessage = "Chưa nhập họ KH")]
        [StringLength(50)]
        public string HoKH { get; set; }

        [DisplayName("Tên KH")]
        [Required(ErrorMessage = "Chưa nhập Tên KH")]
        [StringLength(50)]
        public string TenKH { get; set; }

        [DisplayName("Số CCCD KH")]
        [Required(ErrorMessage = "Chưa nhập CCCD")]
        [StringLength(12)]
        public string CCCD { get; set; }

        [DisplayName("Giới tính")]
        [Required(ErrorMessage = "Chưa nhập Giới tính")]
        public string GioiTinh { get; set; }

        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Chưa nhập SDT")]
        [StringLength(10)]
        public string SDT { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Chưa nhập email")]
        [StringLength(50)]
        public string Email { get; set; }

        [DisplayName("Tài khoản")]
        [StringLength(50)]
        public string TKKH { get; set; }
        [DisplayName("Mật khẩu")]
        [StringLength(30)]
        public string MKKH { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDatPhong> HoaDonDatPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDichVu> HoaDonDichVus { get; set; }
    }
}
