//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132204.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoaiPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiPhong()
        {
            this.Phongs = new HashSet<Phong>();
        }

        [DisplayName("Mã Loại phòng")]
        [Required(ErrorMessage = "Chưa nhập mã loại phòng")]
        [StringLength(10)]
        public string MaLoaiPhong { get; set; }

        [DisplayName("Tên loại phòng")]
        [Required(ErrorMessage = "Chưa nhập tên loại phòng")]
        [StringLength(50)]
        public string TenLoaiPhong { get; set; }

        [DisplayName("Giá")]
        [Required(ErrorMessage = "Chưa nhập Giá")]
        public int Gia { get; set; }

        [DisplayName("Ảnh")]
        [Required(ErrorMessage = "Chưa nhập ảnh")]
        [StringLength(50)]
        public string Anh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
