//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132204.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.HoaDonDatPhongs = new HashSet<HoaDonDatPhong>();
            this.HoaDonDichVus = new HashSet<HoaDonDichVu>();
        }

        [DisplayName("Mã Phòng")]
        [Required(ErrorMessage = "Chưa nhập mã phòng")]
        [StringLength(10)]
        public string MaPhong { get; set; }

        [DisplayName("Tên phòng")]
        [Required(ErrorMessage = "Chưa nhập tên phòng")]
        [StringLength(20)]
        public string TenPhong { get; set; }

        [DisplayName("Mã loại phòng")]
        [Required(ErrorMessage = "Chưa nhập mã loại phòng")]
        [StringLength(10)]
        public string MaLoaiPhong { get; set; }

        [DisplayName("Trạng thái")]
        [Required(ErrorMessage = "Chưa nhập trạng thái")]
        public bool TrangThai { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDatPhong> HoaDonDatPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDichVu> HoaDonDichVus { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
